=== Dwaris/InfoLK/03 XML/20180502/kurs.dtd
<!ELEMENT Kurs (Fach, Typ, Stufe, Bezeichner, Unterricht, Lehrer, Sch端ler*)>
<!ELEMENT Fach (#PCDATA)>
<!ELEMENT Typ (#PCDATA)>
<!ELEMENT Stufe (#PCDATA)>
<!ELEMENT Bezeichner (#PCDATA)>
<!ELEMENT Unterricht (Einheit+)>
<!ELEMENT Einheit (Tag, Stunde, Raum?)>
<!ELEMENT Tag (#PCDATA)>
<!ELEMENT Stunde (#PCDATA)>
<!ELEMENT Raum (#PCDATA)>
<!ELEMENT Lehrer (Name, Vorname)>
<!ATTLIST Lehrer
  k端rzel CDATA #REQUIRED
  geschlecht CDATA #REQUIRED
> 
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Vorname (#PCDATA)>
<!ELEMENT Sch端ler (Name, Vorname, Kurssprecher?)>
<!ATTLIST Sch端ler
  geschlecht CDATA #REQUIRED
>
<!ELEMENT Kurssprecher EMPTY>

=== Dwaris/InfoLK/03 XML/20180502/Mathematikkurs.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Kurs SYSTEM "kurs.dtd">
<Kurs>
  <!-- Organisation -->
  <Fach>Mathematik</Fach>
  <Typ>Leistungskurs</Typ>
  <Stufe>11</Stufe>
  <Bezeichner>11-MA-1</Bezeichner>
  <Unterricht>
    <Einheit>
      <Tag>Montag</Tag>
	  <Stunde>3</Stunde>
	  <Raum>M15</Raum>
    </Einheit>
    <Einheit>
      <Tag>Montag</Tag>
	  <Stunde>4</Stunde>
	  <Raum>M15</Raum>
    </Einheit>
    <Einheit>
      <Tag>Mittwoch</Tag>
	  <Stunde>5</Stunde>
      <Raum>M15</Raum>
    </Einheit>
    <Einheit>
      <Tag>Donnerstag</Tag>
	  <Stunde>7</Stunde>
      <Raum>M15</Raum>
    </Einheit>
    <Einheit>
      <Tag>Freitag</Tag>
	  <Stunde>1</Stunde>
      <Raum>M15</Raum>
    </Einheit>
  </Unterricht>
  <!-- Personen -->
  <Lehrer kürzel="SW" geschlecht="w">
    <Name>Schwarz</Name>
	<Vorname>Michaela</Vorname>
  </Lehrer>
  <Schüler geschlecht="m">
    <Name>Beyer</Name>
	<Vorname>Alexander</Vorname>
  </Schüler>
  <Schüler geschlecht="w">
    <Name>Baum</Name>
	<Vorname>Nina</Vorname>
  </Schüler>
  <Schüler geschlecht="w">
    <Name>Müller</Name>
	<Vorname>Katrin</Vorname>
  </Schüler>
  <Schüler geschlecht="m">
    <Name>Dinc</Name>
	<Vorname>Yunus</Vorname>
  </Schüler>
  <!-- ... -->
</Kurs>

=== Dwaris/InfoLK/03 XML/20180502/BildendeKunst.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Kurs SYSTEM "kurs.dtd">
<Kurs>
  <!-- Organisation -->
  <Fach>Bildende Kunst</Fach>
  <Typ>Grundkurs</Typ>
  <Stufe>11</Stufe>
  <Bezeichner>11-bk-1</Bezeichner>
  <Unterricht>
    <Einheit>
        <Tag>Mittwoch</Tag>
        <Stunde>3</Stunde>
	    <Raum>M41</Raum>
    </Einheit>
    <Einheit>
        <Tag>Mittwoch</Tag>
        <Stunde>3</Stunde>
        <Raum>M41</Raum>
    </Einheit>
    <Einheit>
	    <Tag>Mittwoch</Tag>
        <Stunde>3</Stunde>
        <Raum>M41</Raum>
    </Einheit>
  </Unterricht>
  <!-- Personen -->
  <Lehrer kürzel="SW" geschlecht="m">
    <Name>Schmitt</Name>
	<Vorname>Peter</Vorname>
  </Lehrer>
  <Schüler geschlecht="m">
    <Name>Beyer</Name>
	<Vorname>Alexander</Vorname>
  </Schüler>
  <Schüler geschlecht="w">
    <Name>Baum</Name>
	<Vorname>Nina</Vorname>
    <Kurssprecher/>
  </Schüler>
  <Schüler geschlecht="w">
    <Name>Müller</Name>
	<Vorname>Katrin</Vorname>
  </Schüler>
  <Schüler geschlecht="m">
    <Name>Dinc</Name>
	<Vorname>Yunus</Vorname>
  </Schüler>
  <!-- ... -->
</Kurs>

=== Dwaris/InfoLK/03 XML/20180502/Biologiekurs.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Kurs SYSTEM "kurs.dtd">
<Kurs>
  <!-- Organisation -->
  <Fach>Biologie</Fach>
  <Typ>Grundkurs</Typ>
  <Stufe>11</Stufe>
  <Bezeichner>11-bi-2</Bezeichner>
  <Unterricht>
      <Einheit>
        <Tag>Montag</Tag>
        <Stunde>1</Stunde>
      </Einheit>
      <Einheit>
        <Tag>Montag</Tag>
        <Stunde>2</Stunde>
      </Einheit>
      <Einheit>
	    <Tag>Donnerstag</Tag>
        <Stunde>6</Stunde>
      </Einheit>
  </Unterricht>
  <!-- Personen -->
  <Lehrer kürzel="HO" geschlecht="w">
    <Name>Hoffmann</Name>
	<Vorname>Christine</Vorname>
  </Lehrer>
  <Schüler geschlecht="m">
    <Name>Beyer</Name>
	<Vorname>Alexander</Vorname>
  </Schüler>
  <Schüler geschlecht="w">
    <Name>Baum</Name>
	<Vorname>Nina</Vorname>
  </Schüler>
  <Schüler geschlecht="m">
    <Name>Müller</Name>
	<Vorname>Katrin</Vorname>
  </Schüler>
  <Schüler geschlecht="m">
    <Name>Dinc</Name>
	<Vorname>Yunus</Vorname>
  </Schüler>
  <!-- ... -->
</Kurs>

=== Dwaris/InfoLK/03 XML/20180502/Englischkurs.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Kurs SYSTEM "kurs.dtd">
<Kurs>
  <!-- Organisation -->
  <Fach>Englisch</Fach>
  <Typ>Grundkurs</Typ>
  <Stufe>11</Stufe>
  <Bezeichner>11-en-3</Bezeichner>
  <Unterricht>
    <Einheit>
      <Tag>Montag</Tag>
	  <Stunde>5</Stunde>
	  <Raum>A30</Raum>
    </Einheit>
    <Einheit>
      <Tag>Montag</Tag>
	  <Stunde>5</Stunde>
	  <Raum>A23</Raum>
    </Einheit>
    <Einheit>
      <Tag>Donnerstag</Tag>
	  <Stunde>2</Stunde>
      <Raum>A23</Raum>
    </Einheit>
  </Unterricht>
  <!-- Personen -->
  <Lehrer kürzel="SW" geschlecht="w">
    <Name>Bender</Name>
	<Vorname>Michael</Vorname>
  </Lehrer>
  <Schüler geschlecht="m">
    <Name>Beyer</Name>
	<Vorname>Alexander</Vorname>
  </Schüler>
  <Schüler geschlecht="w">
    <Name>Baum</Name>
	<Vorname>Nina</Vorname>
  </Schüler>
  <Schüler geschlecht="w">
    <Name>Müller</Name>
	<Vorname>Katrin</Vorname>
  </Schüler>
  <Schüler geschlecht="m">
    <Name>Dinc</Name>
	<Vorname>Yunus</Vorname>
  </Schüler>
  <!-- ... -->
</Kurs>

=== Dwaris/InfoLK/03 XML/20180502/Informatikkurs.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Kurs SYSTEM "kurs.dtd">
<Kurs>
  <!-- Organisation -->
  <Fach>Informatik</Fach>
  <Typ>Grundkurs</Typ>
  <Stufe>11</Stufe>
  <Bezeichner>11-inf-1</Bezeichner>
  <Unterricht>
    <Einheit>
      <Tag>Montag</Tag>
	  <Stunde>7</Stunde>
	  <Raum>B04</Raum>
    </Einheit>
    <Einheit>
      <Tag>Mittwoch</Tag>
	  <Stunde>3</Stunde>
    </Einheit>
    <Einheit>
      <Tag>Mittwoch</Tag>
	  <Stunde>4</Stunde>
    </Einheit>
  </Unterricht>
  <!-- Personen -->
  <Lehrer kürzel="SU" geschlecht="w">
    <Name>Schuster</Name>
	<Vorname>Christiane</Vorname>
  </Lehrer>
  <Schüler geschlecht="m">
    <Name>Schwarz</Name>
	<Vorname>Tobias</Vorname>
  </Schüler>
  <Schüler geschlecht="w">
    <Name>Baum</Name>
	<Vorname>Nina</Vorname>
  </Schüler>
  <Schüler geschlecht="w">
    <Name>Müller</Name>
	<Vorname>Katrin</Vorname>
	<Kurssprecher/>
  </Schüler>
  <Schüler geschlecht="m">
    <Name>Roth</Name>
	<Vorname>Andreas</Vorname>
  </Schüler>
  <!-- ... -->
</Kurs>
